### ISSUE TITLE
POST /Shipments should require fromId and toId parameters

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#13]
When creating a new shipment using `POST /Shipments`, the ERP service allows allows shipments to be created without the `fromId` or `toId` parameters in the payload. All shipments require these fields to be valid, so these should be added as required fields to this method. If a caller does not include those parameters in the request, the API should return `422` since there are no default values for these fields.

**Comment by jakepeyser** [comment]
Did you deploy a new version with this change?

**Comment by l2fprod** [comment]
No - I'm not touching the production version without the toolchain.

**Comment by jakepeyser** [comment]
Ok figured. I'll test this with a local instance when I have some time today

**Comment by jakepeyser** [comment]
Deployed updated app with [new toolchain](https://new-console.ng.bluemix.net/devops/toolchains/ad9beed3-e767-4648-8d1e-506771e2c42b). Tested and LGTM
