### ISSUE TITLE
POST /Shipments allows invalid fromId and toId parameters

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#14]
When creating a new shipment using `POST /Shipments`, the ERP service allows allows shipments to be created with invalid `status`, `fromId`, or `toId` parameters in the payload. This means that shipments can be created with an erroneous status (e.g. "BLAH") or corresponding retailers and/or distribution centers that do not exist. These fields need to be checked upon receipt and if they are invalid, a response code of `422` should be returned.

**Comment by l2fprod** [comment]
Loopback does not appear to generate any foreign keys in the database or to check this on its own, despite the model correctly defining a foreign key relationship.

https://github.com/strongloop/loopback-connector-mysql/issues/16
https://github.com/strongloop/loopback-connector-mysql/issues/135
http://stackoverflow.com/questions/34790938/loopback-foreign-key-validation?rq=1

A "before save" Model hook should do it. Ideally it could be a generic solution checking all fields of an object pointing to another object.

**Comment by jakepeyser** [comment]
LGTM
