### ISSUE TITLE
Missing Product in Initial Dataset

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#15]
When a new Demo is created, the `Product` with ID 101 is missing from the initial dataset. Since this is not the final dataset this is not a huge issue in itself, however, the only `Inventory` objects in existence upon initialization correspond to that product. We either need to put that product back in the initial dataset or create different initial Inventory objects so that other API methods are testable upon creation of a new demo session.

**Comment by l2fprod** [comment]
LGTM

argh... it happened when I prefixed the ID with "10" to get in them in the hundred area, although the product ID 1 became 100 but in inventory.js, I prefixed it with 10 instead of adding 00.
