### ISSUE TITLE
Service Discovery - ERP

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#19]
Implement service registration and heartbeats for the ERP app. Look at using the [Service Discovery JS client](https://github.ibm.com/alchemy-servicediscovery/jsclient) for this task

See [#55](https://github.com/IBM-Bluemix/logistics-wizard/issues/55)

**Comment by jakepeyser** [comment]
Please register the ERP service with:
```json
{
    "tags": ["logistics-wizard","database"],
    "status": "UP",
    "service_name": "lw-erp",
    "ttl": 300,
    "endpoint": {
        "value": "https://logistics-wizard-erp.mybluemix.net",
        "type": "http"
    }
}
```

**Comment by jakepeyser** [comment]
@rvennam I see you are registering your app with a `/` suffix. Can you remove this as my code assumes that the endpoint will end in `.net`?

**Comment by rvennam** [comment]
Yup, Will change this with the next drop.

**Comment by l2fprod** [comment]
@rvennam: I'll review the changes
