### ISSUE TITLE
DistributionCenter/{id}/inventories return inventory data from other demo environment

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-erp#21]
Since the DistributionCenter is not an "isolated" model, the demoId is not injected in the where clause when querying inventories.

**Comment by jakepeyser** [comment]
I am still getting a `200` response code and an empty array when I hit `api/v1/DistributionCenters/xxx/inventories` where xxx is a non-existent distribution center. I am expecting a 404 and this causes my [respective controller unit test](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/server/tests/test_distribution_centers_service.py) to fail.

**Comment by rvennam** [comment]
@jakepeyser @l2fprod please review

**Comment by jakepeyser** [comment]
LGTM now after #23 resolved my issue
