### ISSUE TITLE
Too many connections error

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#24]
As noted in #18, I was getting numerous issues about "too many connections" when I start my ERP app locally using the (at the time) ElephantSQL DB credentials
```
{ [error: too many connections for role "psiiudfi"]
  name: 'error',
  length: 103,
  severity: 'FATAL',
  code: '53300',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'miscinit.c',
  line: '480',
  routine: 'InitializeSessionUserId' }
```
Issue is no longer appearing, but opening this issue just in case we see it in the near future

**Comment by l2fprod** [comment]
@jakepeyser:
ElephantSQL has only 5 connections. How did you define your datasource json? If you put 5 for the "max" pool value and if you open the ElephantSQL dashboard as example then you can get this type of issue.

**Comment by jakepeyser** [comment]
Yes, I realize there is a connection max but it seems to me that the app makes more than one connection at a time. I fined the data source just like you said. Noticed this issue again with a new service instance, the dashboard open, and only 2 app instances calling it.

**Comment by l2fprod** [comment]
Loopback establishes a pool of "max" connections. If you have 2 app instances plus the console, you are likely to go over the 5 connections.  The base plan of ElephantSQL is too small for multiple instances of the ERP service.

**Comment by jakepeyser** [comment]
As discussed in Slack, this is a limitation of the free tier of ElephantSQL in conjunction with loopback connection pooling. This should be explained in the wiki and mentioned in an FAQ of possible issues.

**Comment by jakepeyser** [comment]
LGTM, thanks for adding that clarification. I will add an FAQ page of common issues and link there for more info

**Comment by jakepeyser** [comment]
Added [explanation on the new FAQ page](https://github.com/IBM-Bluemix/logistics-wizard/wiki/FAQ#the-erp-simulator-app-is-throwing-a-too-many-connections-error-on-startup)
