### ISSUE TITLE
Connect to DB dynamically

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#25]
The ERP simulator should connect to the correct ElephantSQL DB instance by using a dynamic service name. For instance, if in `LOGISTICS_WIZARD_ENV=DEV` it should connect to `dev-logistics-wizard-erp-db`. The toolchain must be updated in conjunction so that separate ElephantSQL service instances are created for dev and prod.

**Comment by l2fprod** [comment]
@jakepeyser 

The ERP service currently picks the first ElephantSQL db in VCAP_SERVICES (in datasources.local.js).

How do you plan to configure the app? Will you bind multiple ElephantSQL services to the app and expect the app to pick the right one based on the ENV?

Using different manifest files could be another option if we want to have multiple instances (dev, prod) of the app in the same Bluemix space.

**Comment by jakepeyser** [comment]
The plan is to have all apps/services in the same space (to accommodate free trial users), so we can't just pick the first instance. I am dynamically binding the correct service in the pipeline, but the manifest would override that. I like the idea of multiple manifests instead.

**Comment by rvennam** [comment]
Following [these guidelines: Multiple Manifests with Inheritance](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#multi-manifests), we can have a base `manifest.yml` and then `dev-manifest.yml` and `prod-manifest.yml`

**Comment by rvennam** [comment]
Inheritance appears to be broken. Contents (application block) in the child manifest are NOT overriding the parent manifest.

**Comment by jakepeyser** [comment]
Tested and LGTM, I am fine with manifests with duplicate info for now since they are so small. Still, @rvennam can you raise this issue with the Runtimes team?
