### ISSUE TITLE
Implement session management in the context of a live shared demo

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-erp#3]
If multiple users are using a shared instance and running a standard scenario, we don't want the action of one user impacting another user. Basically this means mutable data should not be shared across users.

This should apply only to the use case where the simulator is used. In this setup, Loopback and https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-loaded could be used to intercept calls and filter results to only return objects related to the user playing with the demo. This "access" hook https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-access shows an example with a "tenantId" filter added to any request - sounds nice!

**Comment by JakePeyser** [comment]
@l2fprod merged your repo issues so we have only one pipeline

**Comment by JakePeyser** [comment]
I believe this is covered by [#50](https://github.com/IBM-Bluemix/logistics-wizard/issues/50) and can be closed as a duplicate, however, we still need to explicitly lay out how this will work end-to-end

**Comment by l2fprod** [comment]
Not really. This task will cover partitioning the shipment/inventory data by demo session. It is independent from the token design.

**Comment by JakePeyser** [comment]
Wrong issue, I meant  [#30](https://github.com/IBM-Bluemix/logistics-wizard/issues/30). Unless this is the implementation and that is the design

**Comment by l2fprod** [comment]
@JakePeyser indeed #30 is the design where we all contribute, #3 is the implementation for the ERP service.

**Comment by l2fprod** [comment]
found a solution using the Model.checkAccess (since operation hooks and loopback.getCurrentContext() have issues). Work done in https://github.com/IBM-Bluemix/logistics-wizard-erp/tree/data_isolation - to be merged after some more testing.

**Comment by JakePeyser** [comment]
I like this solution, so LGTM. I've updated the [Data Models wiki page](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Data-Models) to model this change.

@benrondeau @shenybluemix @bluemareks: Please review this, as it is integral in the way we will be modeling data ownership in the system
