### ISSUE TITLE
Update Basic Simulator Deployment README

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard-erp#32]
The README for [Basic configuration with the Logistics Wizard ERP simulator](https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/README-BASIC.md) needs to be updated. Some suggested updates:
- [x] reformat [Loopback section](https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/README-BASIC.md#building-an-api-with-swagger-and-loopbackio) and point to [related blog post](https://developer.ibm.com/bluemix/2016/07/11/building-smarter-supply-chain-developer-journey-loopback/) where it makes sense
- [x] remove [Service Discovery section](https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/README-BASIC.md#building-an-api-with-swagger-and-loopbackio) as it will be discussed in an upcoming blog post instead
- [x] add section on deployment to Bluemix (i.e. https://github.com/IBM-Bluemix/logistics-wizard#running-the-app-on-bluemix)
- [x] add D2B and link to [Toolchain](https://github.com/IBM-Bluemix/logistics-wizard-toolchain), mentioning deployment of full system
- [x] add section detailing unit testing and point to wiki page updates (#31)

**Comment by l2fprod** [comment]
https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/3ab6e59611b873a96e3ea937223080199b963c46
https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/764a62abcfa93e9e424adc9655b1657681e9639b
https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/8bc85e4a409c75a5a171755495410df7720f6368

**Comment by l2fprod** [comment]
@jakepeyser 

I have not updated https://github.com/IBM-Bluemix/logistics-wizard/wiki/Testing. I don't get the point of this separate Wiki page. How to run the unit tests is tightly linked to the code, better to keep them close. It fits better in a .md file in the code repo (like the current README).

**Comment by jakepeyser** [comment]
hmm I was thinking a consolidated "Testing" section would be better since we will have 3+ different apps...but maybe you are right since it is contextual to the code. @rvennam thoughts?
