### ISSUE TITLE
Implement security/right management on the ERP data

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard-erp#4]
https://docs.strongloop.com/display/public/LB/Controlling+data+access will be of help to configure the API right management

Refer to https://github.com/IBM-Bluemix/logistics-wizard/wiki/Personas for the required roles

Step 1 is to disable all access unless you are logged in. Roles will come after.

**Comment by JakePeyser** [comment]
@l2fprod merged your repo issues so we have only one pipeline

**Comment by JakePeyser** [comment]
Aside from comment on [#61](https://github.com/IBM-Bluemix/logistics-wizard/issues/61), LGTM
