### ISSUE TITLE
Technical Collateral for ERP Service

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard-erp#6]
_From @JakePeyser on May 3, 2016 4:19_

Plan out the content items that would be useful to developers/CIOs/etc for the ERP component. Ensure they all tie back to the value of the service and why Bluemix is being used.

Also, compile and send @jakepeyser examples you would like the digital agency to use as reference points. For example, this [Natural Language Classifier graphic video](https://www.youtube.com/watch?v=h1ZiUIvYdD8)

Story #5 

_Copied from original issue: IBM-Bluemix/logistics-wizard#36_

**Comment by l2fprod** [comment]
updated https://github.com/IBM-Bluemix/logistics-wizard/wiki/Technical-Collateral with ideas where the ERP service can be leveraged - something we need to update as we go through the implementation.
